version: "3"

services:
  meta:
    build: .
    command: cron
    environment:
      MODE: master
    volumes:
      - "./caches:/app/caches"
      - "./upstream:/app/upstream"
      - "./polymc:/app/polymc"
      - "./public:/app/public"
      - "./config:/app/config"
